version: '3.8'
services:

  dynamodb:
    image: instructure/dynamo-local-admin
    container_name: dynamodb
    ports:
      - "8010:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    networks:
      - stats-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - stats-net

networks:
  stats-net:
    driver: bridge