spring:
  profiles:
    active: local
  application:
    name: user-interaction-statistics
  main:
    web-application-type: reactive
  devtools:
    add-properties: true

app:
  events:
    exchange: amq.direct
    routing-key: event.stats.validated
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    access-key: fakeMyKeyId
    secret-key: fakeSecretAccessKey
    table-name: stats-table

logging:
  level:
    root: INFO
    co.com.bancolombia: DEBUG

server:
  port: 8080

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"